name: CI-CD_Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Cache packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release
    - name: Publish Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Project_CI-CD
        path: /home/runner/work/CI-CD/CI-CD/bin/Release/netcoreapp3.1/publish/
        
    - name: AWS cli install action
      uses: chrislennon/action-aws-cli@1.1
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: Create CodeDeploy Deployment
      run: |
        aws deploy create-deployment \
          --application-name DemoApplication \
          --deployment-group-name DemoApp_DeploymentGroup \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --s3-location "bucket=codepipeline-us-east-2-475258622142, bundleType=zip"
          
